### ISSUE TITLE
[Give 2.0.5] New: exclude your sensitive  addon setting from export

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give-docs#144]
**URL:** https://github.com/WordImpress/Give/issues/2716

**PROBLEM:** We have a feature in `Give` core to export plugin settings, but some add-ons like payment gateways have sensitive information which admin does not want to expose accidentally. We created a logic in `Give 2.0.5` to protect them from exporting.

**SOLUTION:** After `Give 2.0.5`, you can exclude you setting. For example:
```
add_filter( 'settings_export_excludes', function( $excludes ) {
	$excludes['plaid_client_id']  = 'Plaid Client ID';
	$excludes['plaid_public_key'] = 'Plaid Public Key';

	return $excludes;
});
```
for ref: https://github.com/WordImpress/Give/pull/2829

**Comment by marutim** [comment]
Started Doc: https://docs.google.com/document/d/1Fq5MZuS6MoLVWLQ2FOc7xfBuT_jlN0NxEts-Zyv21_M

**Comment by marutim** [comment]
I completed the doc.

@mathetos Please review and let me know where can we publish it.

**Comment by mathetos** [comment]
@marutim I edited this heavily and published it here:
https://givewp.com/documentation/core/tools/exports-tab/export-settings-from-exports/

But I also re-opened the original issue for @ravinderk to review because that filter really should be properly prefixed. Maruti, please monitor the original issue and when the filter is live in the plugin update the article with the proper prefix.

Thanks gang!

**Comment by marutim** [comment]
Updated the filter from `settings_export_excludes` to `give_settings_export_excludes` in the doc.
