### ISSUE TITLE
web-doc: update setting default gateway per form

### ISSUE THREAD

**Issue by marutim** [impress-org/give-docs#175]
## Necessary Items
**User Story** 
User has been following this doc which confuses regarding the position of the "Default gateway" option per form.

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Current Url:**|https://givewp.com/addons/per-form-gateways/|*required*|

## Assets
![edit donation form wp give wordpress](https://user-images.githubusercontent.com/3498917/41309966-c13ab558-6e9d-11e8-8fcf-ab0c4a8bd429.png)

## Related Give Core/Add-on issues
HS link: https://secure.helpscout.net/conversation/595721858/19762?folderId=672199

## Acceptance Criteria

**This doc is ready to publish when:**
- [ ] I understand how to update default gateways.
- [ ] Update the screenshot with the latest visuals.

**Comment by mathetos** [comment]
@marutim On this doc, I think there are several things that need to be clarified still:

1. A section explaining the relationship between the Default Gateway setting, and this Addon. Essentially, what happens if you keep it set to "Global Default", but with this addon you disable the Global Default gateway? 
2. A screenshot like what you have above would be helpful as well.

Let me know when those edits have been made and I'll review. Thanks!

**Comment by marutim** [comment]
@mathetos I have added a section at the bottom of this doc https://givewp.com/documentation/add-ons/per-form-gateways/ explaining the relationship between the default gateway and the per form gateway options.

Please review and let me know of any changes. Thanks!

**Comment by mathetos** [comment]
Good work here. I made some minor tweaks and updates. Thanks!
