### ISSUE TITLE
web-doc: update exports tab to include settings for add-ons

### ISSUE THREAD

**Issue by marutim** [impress-org/give-docs#191]
## Necessary Items
**User Story** 
As a user, I would like to see documentation about the export functionalities when addons like Gift Aid and recurring is activated

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Current Url:**|https://givewp.com/documentation/core/tools/exports-tab/|*required*|

## Assets
![image](https://user-images.githubusercontent.com/3498917/46409833-8a75c180-c734-11e8-947e-744f4d714e5d.png)

## Acceptance Criteria
List what will make this doc ready to publish. 

**This doc is ready to publish when:**
- [ ] I see documentation about exporting Gift Aid Donations
- [ ] I see documentation about upcoming subscriptions renewals.

**Comment by mathetos** [comment]
I'm not sure that is the place to put that information. That section of docs is about Give Core only. The Gift Aid export option is already documented in the Gift Aid docs section here:
https://givewp.com/documentation/add-ons/gift-aid/exporting-gift-aid-data/

But the Recurring Donations Export is *NOT* documented here:
https://givewp.com/documentation/add-ons/recurring-donations/

So I'd like to limit the scope of this issue to the following:

Add new "Exporting Upcoming Renewals" doc as sub-page here: https://givewp.com/documentation/add-ons/recurring-donations/

This doc is ready to publish when:

- [ ]  I see documentation about upcoming subscriptions renewals. 
- [ ] The new doc shows where to find this tool
- [ ] The new doc explains clearly what to expect when using this tool
- [ ] The new doc explains what happens when NO upcoming subscriptions are available

**Comment by marutim** [comment]
I agree, we would need to have other docs for these settings which is specific to that addon but I would also like to have links in the Give core export tab https://givewp.com/documentation/core/tools/exports-tab/ that links to these extra settings with addons( may be in the sidebar or towards the bottom of the doc ) for better user experience.

**Comment by mathetos** [comment]
@marutim I'm assigning you this one for now, create a Google doc to take it as far as you can and I'll review carefully when you've got that ready.

**Comment by marutim** [comment]
@mathetos I have worked on this doc directly on the website but have kept the doc in draft so that you can review it before publishing it.
I have created this as a subpage to recurring donations.

Link to the preview draft: https://givewp.com/?post_type=documentation&p=324564&preview=true

**Comment by Benunc** [comment]
cleaned this up and published. well done, @marutim!
